import type { Guard, GuardOutcome } from '../../guards.js'
import { joinDateToKstDay, kstDayOf } from '../../kst.js'

/**
 * Naver writes this under the joining member's own name the moment they are
 * admitted, so its presence is proof of a new member and needs no lookup. The
 * cafe manager cannot change the wording — the only welcome text the admin
 * screens expose is the one shown on the join confirmation page, not this.
 */
function autoGreetingText(nickname: string): string {
  return `${nickname}님이 우리 카페에 가입하였습니다.\n댓글로 ${nickname}님을 환영해주세요.`
}

/**
 * Compared as whole strings rather than matched by pattern. A nickname may hold
 * regex metacharacters, and requiring the body's nickname to be the author's
 * own means the wording cannot be borrowed under another name.
 *
 * The comparison is against the normalised body: the page stores spaces as
 * `&nbsp;` and breaks as `<br>`, and `parseMemoList` has already turned those
 * into ordinary spaces and newlines.
 */
export function isAutoGeneratedGreeting(post: {
  readonly bodyText: string | null
  readonly authorNickname: string | null
}): boolean {
  if (post.bodyText === null || post.authorNickname === null) return false
  return post.bodyText === autoGreetingText(post.authorNickname)
}

/**
 * Greets only members who joined recently. Join dates carry no time, so the
 * window is counted in whole KST calendar days and never in hours. The window
 * is measured from the day the session runs, not the day the post was written.
 */
export const newMemberGuard: Guard = (candidate, ctx): GuardOutcome => {
  if (isAutoGeneratedGreeting(candidate)) return null
  if (ctx.authorMembership.kind === 'NOT_TRACKED') {
    return { kind: 'SKIP', reason: 'NOT_NEW_MEMBER' }
  }
  const joinDay = joinDateToKstDay(ctx.authorMembership.joinDate)
  // The parser only stores dates it could read, so this means the stored shape
  // changed under us rather than that the member is old.
  if (joinDay === null) return { kind: 'RISK', flag: 'STRUCTURE_CHANGED' }

  const nowDay = kstDayOf(ctx.nowMs)
  return nowDay - joinDay <= ctx.newMemberWindowDays
    ? null
    : { kind: 'SKIP', reason: 'NOT_NEW_MEMBER' }
}
