import { describe, expect, it } from 'vitest'
import {
  isAutoGeneratedGreeting,
  newMemberGuard,
} from '../../../../src/shared/automations/welcome-comment/newMember.js'
import type { GuardContext } from '../../../../src/shared/guards.js'
import type { AuthorMembership, Candidate } from '../../../../src/shared/types.js'

/** 2026-08-23 12:00 KST. */
const POSTED_AT = Date.UTC(2026, 7, 23, 3, 0)

const autoGreeting = (nickname: string): string =>
  `${nickname}님이 우리 카페에 가입하였습니다.\n댓글로 ${nickname}님을 환영해주세요.`

function candidate(overrides: Partial<Candidate> = {}): Candidate {
  return {
    automationId: 'welcome-comment',
    cafeId: '10000000',
    boardId: '5',
    postId: '1001',
    title: null,
    bodyText: '안녕하세요 잘부탁드립니다',
    authorNickname: '가입자하나',
    authorId: 'member-1',
    postedAt: POSTED_AT,
    ...overrides,
  }
}

function ctx(membership: AuthorMembership, windowDays = 7): GuardContext {
  return {
    nowMs: POSTED_AT,
    operatorAccounts: [],
    existingCommentAuthors: [],
    authorMembership: membership,
    newMemberWindowDays: windowDays,
  }
}

describe('isAutoGeneratedGreeting', () => {
  it('matches the wording naver writes under the joining member', () => {
    expect(isAutoGeneratedGreeting({ bodyText: autoGreeting('가입자하나'), authorNickname: '가입자하나' })).toBe(true)
  })

  // The nickname in the body must be the author's, so copying the wording
  // under a different name does not pass as an auto-generated post.
  it('rejects the wording written under someone else name', () => {
    expect(isAutoGeneratedGreeting({ bodyText: autoGreeting('가입자하나'), authorNickname: '가입자둘' })).toBe(false)
  })

  it('rejects a greeting the member wrote themselves', () => {
    expect(isAutoGeneratedGreeting({ bodyText: '안녕하세요 잘부탁드립니다', authorNickname: '가입자하나' })).toBe(false)
  })

  it('rejects a post with nothing to compare', () => {
    expect(isAutoGeneratedGreeting({ bodyText: null, authorNickname: '가입자하나' })).toBe(false)
    expect(isAutoGeneratedGreeting({ bodyText: autoGreeting('x'), authorNickname: null })).toBe(false)
  })
})

describe('newMemberGuard', () => {
  it('passes an auto-generated post without consulting the table', () => {
    const post = candidate({ bodyText: autoGreeting('가입자하나') })
    expect(newMemberGuard(post, ctx({ kind: 'NOT_TRACKED' }))).toBeNull()
  })

  it('passes a member who joined inside the window', () => {
    expect(newMemberGuard(candidate(), ctx({ kind: 'JOINED', joinDate: '2026.08.23.' }))).toBeNull()
  })

  it('passes a member who joined exactly N days ago', () => {
    expect(newMemberGuard(candidate(), ctx({ kind: 'JOINED', joinDate: '2026.08.16.' }))).toBeNull()
  })

  it('skips a member who joined one day beyond the window', () => {
    expect(newMemberGuard(candidate(), ctx({ kind: 'JOINED', joinDate: '2026.08.15.' }))).toEqual({
      kind: 'SKIP',
      reason: 'NOT_NEW_MEMBER',
    })
  })

  it('skips a self-written greeting from someone the table never saw', () => {
    expect(newMemberGuard(candidate(), ctx({ kind: 'NOT_TRACKED' }))).toEqual({
      kind: 'SKIP',
      reason: 'NOT_NEW_MEMBER',
    })
  })

  it('raises a risk flag when a stored join date is not the shape we store', () => {
    expect(newMemberGuard(candidate(), ctx({ kind: 'JOINED', joinDate: 'garbage' }))).toEqual({
      kind: 'RISK',
      flag: 'STRUCTURE_CHANGED',
    })
  })
})
