import { isAutoGeneratedGreeting } from '../shared/automations/welcome-comment/newMember.js'
import { kstDayOf, kstDayToJoinDate } from '../shared/kst.js'
import { MEMBER_PAGE_SIZE } from '../shared/members.js'
import { TIMEOUTS, type RawCandidate } from '../shared/protocol.js'
import type { AuthorMembership } from '../shared/types.js'
import type { MembersRepo } from './db/membersRepo.js'
import type { ExtensionTransport } from './ws/server.js'

/**
 * A long outage is the only thing that walks past a page or two. The cafe has
 * hundreds of thousands of members, so the walk needs a floor.
 */
const MAX_PAGES = 20

export interface MembershipDeps {
  readonly transport: ExtensionTransport
  readonly repo: MembersRepo
  readonly cafeId: string
  readonly windowDays: number
  readonly nowMs: number
  readonly newRequestId: () => string
}

/**
 * `'DEFER'` means the answer is unknown this session, not that the author is
 * old. The orchestrator holds such a post and leaves the watermark where it is.
 */
export type MembershipResolver = (raw: RawCandidate) => AuthorMembership | 'DEFER'

async function fetchPage(deps: MembershipDeps, page: number) {
  try {
    const reply = await deps.transport.request(
      {
        type: 'FETCH_MEMBERS',
        requestId: deps.newRequestId(),
        cafeId: deps.cafeId,
        page,
        perPage: MEMBER_PAGE_SIZE,
      },
      TIMEOUTS.fetchMembersMs,
    )
    return reply.type === 'MEMBERS' ? reply.members : null
  } catch {
    return null
  }
}

/**
 * Fills the table forward from the newest joins. The first run takes one page
 * and stops: the tool does not reach back for people who joined before it
 * started looking, exactly as the post watermark does not reach back for older
 * posts. Later runs stop as soon as a page holds somebody already stored.
 */
async function refresh(deps: MembershipDeps): Promise<boolean> {
  const firstRun = deps.repo.isEmpty(deps.cafeId)

  for (let page = 1; page <= MAX_PAGES; page += 1) {
    const members = await fetchPage(deps, page)
    if (members === null) return false
    if (members.length === 0) return true

    // Checked before storing, or every member would look already known.
    const reachedKnown = members.some(
      (member) => deps.repo.joinDateOf(deps.cafeId, member.memberKey) !== null,
    )
    deps.repo.upsertMany(deps.cafeId, members)

    if (firstRun || reachedKnown) return true
  }
  return true
}

export async function createMembershipResolver(deps: MembershipDeps): Promise<MembershipResolver> {
  const fresh = await refresh(deps)

  if (fresh) {
    // One day beyond the window: the backlog brake lets yesterday's posts
    // through, and judging one needs the people who joined a day earlier still.
    deps.repo.prune(deps.cafeId, kstDayToJoinDate(kstDayOf(deps.nowMs) - (deps.windowDays + 1)))
  }

  return (raw) => {
    if (raw.authorId !== null) {
      const joinDate = deps.repo.joinDateOf(deps.cafeId, raw.authorId)
      if (joinDate !== null) return { kind: 'JOINED', joinDate }
    }
    // The wording alone proves a new member, so a failed refresh cannot hold
    // these back.
    if (isAutoGeneratedGreeting(raw)) return { kind: 'NOT_TRACKED' }
    return fresh ? { kind: 'NOT_TRACKED' } : 'DEFER'
  }
}
