/**
 * Regenerates the CP949 table the extension encodes form bodies with.
 *
 * The table is vendored rather than derived at runtime because the two runtimes
 * disagree: node's `TextDecoder('euc-kr')` implements strict EUC-KR and rejects
 * the extended area chrome accepts, so a table built from the platform would
 * make tests prove something production does not do.
 *
 *   node scripts/generate-cp949.mjs
 */
import { writeFileSync } from 'node:fs'
import iconv from 'iconv-lite'

const LEAD_MIN = 0x81
const LEAD_MAX = 0xfe
const TRAIL_MIN = 0x41
const TRAIL_MAX = 0xfe
const TRAIL_SPAN = TRAIL_MAX - TRAIL_MIN + 1

const slots = []
let mapped = 0

for (let lead = LEAD_MIN; lead <= LEAD_MAX; lead += 1) {
  for (let trail = TRAIL_MIN; trail <= TRAIL_MAX; trail += 1) {
    const bytes = Buffer.from([lead, trail])
    const char = iconv.decode(bytes, 'cp949')
    // Keep only pairs that survive a round trip, so the encode direction the
    // table is used for is the one that was verified here.
    const encodable = char.length === 1 && Buffer.compare(iconv.encode(char, 'cp949'), bytes) === 0
    slots.push(encodable ? char.codePointAt(0) : 0)
    if (encodable) mapped += 1
  }
}

const escaped = slots
  .map((codePoint) => '\\u' + codePoint.toString(16).padStart(4, '0'))
  .join('')

const source = [
  '// Generated by scripts/generate-cp949.mjs. Do not edit by hand.',
  '',
  '/** First lead byte of the double-byte area. */',
  'export const CP949_LEAD_MIN = 0x' + LEAD_MIN.toString(16),
  '/** First trail byte; the row width below counts from here. */',
  'export const CP949_TRAIL_MIN = 0x' + TRAIL_MIN.toString(16),
  'export const CP949_TRAIL_SPAN = ' + TRAIL_SPAN,
  '',
  '/**',
  ' * Index is (lead - CP949_LEAD_MIN) * CP949_TRAIL_SPAN + (trail - CP949_TRAIL_MIN).',
  ' * A NUL slot means that byte pair maps to nothing.',
  ' */',
  'export const CP949_TABLE =',
  "  '" + escaped + "'",
  '',
].join('\n')

writeFileSync('src/shared/cp949Table.ts', source)
console.log(mapped + ' mapped pairs of ' + slots.length + ' slots')
